server:
  port: 8080

com.vakcinainfo:
  defaultvalues:
    limit: 5

spring:
  datasource:
    url: jdbc:h2:file:./db/vaccination
    driverClassName: org.h2.Driver
    username: tt
    password: tt
  jpa:
    hibernate:
      ddl-auto: create-drop
      use-new-id-generator-mappings: true
  h2:
    console:
      enabled: true